BEGIN TRANSACTION;

DROP TABLE IF EXISTS saved_bars;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
 id BIGSERIAL PRIMARY KEY,
 firstname VARCHAR(255) NOT NULL,
 lastname VARCHAR(255) NOT NULL,
 username VARCHAR(15) NOT NULL UNIQUE,
 email VARCHAR(255) NOT NULL UNIQUE,
 password_digest VARCHAR(255) NOT NULL
);

CREATE TABLE saved_bars (
 id BIGSERIAL PRIMARY KEY,
 name VARCHAR(255) NOT NULL,
 rating INTEGER DEFAULT 0,
 phone VARCHAR(255) NOT NULL,
 price VARCHAR(255) NOT NULL,
 address TEXT,
 user_id INTEGER REFERENCES users(id)
);

COMMIT;
